### PR TITLE
bytes/string compatibility fix

### PR DESCRIPTION
**Pull request by pveber**
A simple fix to use mlgmp with compiler version 4.07.

### CODE REVIEW

**Comment by himito** [comment]
Hello @monniaux,

sorry for bothering you, I know that you are a very busy person. 

I'm using your interface for GMP in a tool that needs Ocaml >= 4.08, and I saw that this PR solves the "problem" of patching your code each time that someone wants to compile the tool.

The constraint in the `opam` package is  https://github.com/ocaml/opam-repository/blob/b480fd1eca863bc175a2171834df2d729cbb8773/packages/mlgmp/mlgmp.20120224/opam#L20 

Thank you in advance.
Jaime

**Comment by monniaux** [comment]
Hi 

Done. I had not seen this PR

**Comment by monniaux** [comment]
I fixed other issues. 

> De: "DAVID MONNIAUX" ***@***.***>
> À: "monniaux"
> ***@***.***>
> Cc: "monniaux" ***@***.***>, "Mention"
> ***@***.***>
> Envoyé: Dimanche 18 Décembre 2022 16:34:52
> Objet: Re: [monniaux/mlgmp] bytes/string compatibility fix (#1)

> Hi

> Done. I had not seen this PR

**Comment by himito** [comment]
Thank you so much !

**Pull request merged**
